name: CI - basic

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Info
      run: |
        echo "Runner działa ✅"
        hostname
        whoami
        uname -a
        
    - name: Inspect project
      run: |
        echo "Pliki w repo:"
        ls -la
